version: '3.9'

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: api-app
    working_dir: /var/www
    volumes:
      - ../src:/var/www

  nginx:
    image: nginx:1.24-alpine
    container_name: api-nginx
    restart: always
    ports:
      - '8001:80'
    volumes:
      - ../src:/var/www
      - ./nginx:/etc/nginx/conf.d